//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int Id { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> JobRankType { get; set; }
        public Nullable<int> JobRankLevel { get; set; }
        public Nullable<int> SalaryLevel { get; set; }
        public Nullable<int> SalarySubLevel { get; set; }
    }
}
